context:
  version: "1.0.23"

package:
  name: imgcat
  version: ${{ version }}

source:
  url: https://github.com/danielgatis/imgcat/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 027a5f673b92fa85e993efa48be260c5cc5cb42f421f611741b279b46f1dfb25
  target_directory: src

build:
  number: 0
  skip:
    - win
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -ldflags="-s -w" -v -o ${PREFIX}/bin/imgcat

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - imgcat --help

about:
  homepage: https://github.com/danielgatis/imgcat
  summary: Display images and gifs in your terminal emulator
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/danielgatis/imgcat

extra:
  recipe-maintainers:
    - danielgatis
